version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    container_name: backend

  frontend:
    build:
      context: ./frontend/frontendOnibus/bus-app
    ports:
      - "3000:80"
    container_name: frontend
